imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    serializer:
        enabled: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~
    #serializer:
        #enabled: true

# Twig Configuration
twig:
    cache: false
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port: "%mailer_port%"
#    auth_mode: "%mailer_auth_mode%"
    spool:     { type: memory }

# FosUser Configuration
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: OGIVE\UserBundle\Entity\User
    registration:
        form:
            type: OGIVE\UserBundle\Form\RegistrationType
    profile:
        form:
            type: OGIVE\UserBundle\Form\ProfileType
            
# FOSRestBundle Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: 
        rules:
            #- { path: '^/', priorities: ['json'], fallback_format: 'json'}
    view:
        view_response_listener: true
        formats:
            xml: true
            json : true
            html: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        include_format: false
        

blackford_twilio:
    # (Required) Username to authenticate with, typically your Account SID from www.twilio.com/user/account
    username: "ACdda206efadd5de15c5f0121a6a982a9c"

    # (Required) Password to authenticate with, typically your Auth Token from www.twilio.com/user/account
    password: 'e77b1a26567145aa789a3dc0d701dea0'

    # (Optional) Account Sid to authenticate with, defaults to <username> (typically not required)
    accountSid: 'ACdda206efadd5de15c5f0121a6a982a9c'

    # (Optional) Region to send requests to, defaults to no region selection (typically not required)
    # region: