ogive_alert_domain:
    resource: "@OGIVEAlertBundle/Controller/DomainController.php"
    type:     rest
    
ogive_alert_call_offer:    
    resource: "@OGIVEAlertBundle/Controller/CallOfferController.php"
    type:     rest
    
ogive_alert_additive:
    resource: "@OGIVEAlertBundle/Controller/AdditiveController.php"
    type:     rest

ogive_alert_expressionInterest:
    resource: "@OGIVEAlertBundle/Controller/ExpressionInterestController.php"
    type:     rest
    
ogive_alert_procedureResult:
    resource: "@OGIVEAlertBundle/Controller/ProcedureResultController.php"
    type:     rest
    
ogive_alert_entreprise:
    resource: "@OGIVEAlertBundle/Controller/EntrepriseController.php"
    type:     rest
    
ogive_alert_subscription:
    resource: "@OGIVEAlertBundle/Controller/SubscriptionController.php"
    type:     rest
    
ogive_alert_subscriber:
    resource: "@OGIVEAlertBundle/Controller/SubscriberController.php"
    type:     rest
    
ogive_alert_specialFollowUp:
    resource: "@OGIVEAlertBundle/Controller/SpecialFollowUpController.php"
    type:     rest
    
ogive_alert_telephone:
    resource: "@OGIVEAlertBundle/Controller/TelephoneController.php"
    type:     rest
    
ogive_alert_mail:
    resource: "@OGIVEAlertBundle/Controller/MailController.php"
    type:     rest

ogive_alert_historicalAlertSubscriber:
    resource: "@OGIVEAlertBundle/Controller/HistoricalAlertSubscriberController.php"
    type:     rest
    
ogive_users_controller:
    resource: "@OGIVEUserBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /admin

ogive_alert:
    resource: "@OGIVEAlertBundle/Resources/config/routing.yml"
    prefix:   /

ogive_user:
    resource: "@OGIVEUserBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
       
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#JMSJobQueueBundle:
#    resource: "@JMSJobQueueBundle/Controller/"
#    type: annotation
#    prefix: /jobs