# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
            
    mail_service:
        class: OGIVE\AlertBundle\Services\MailService
        arguments: [@mailer,@templating]
        
    curl_service:
        class: OGIVE\AlertBundle\Services\CurlService
        arguments: ["@service_container"]
        
    sms_service:
        class: OGIVE\AlertBundle\Services\SmsService
        arguments: ["@curl_service"]

    common_service:
        class: OGIVE\AlertBundle\Services\CommonService
        arguments: ["@mail_service", "@sms_service", "@doctrine.orm.entity_manager"]