<?php

namespace OGIVE\AlertBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * AdditiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditiveRepository extends EntityRepository
{
    public function deleteAdditive(\OGIVE\AlertBundle\Entity\Additive $additive) {
        $em= $this->_em;
        $additive->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($additive);
            $em->flush();
            $em->getConnection()->commit();
            return $additive;
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveAdditive(\OGIVE\AlertBundle\Entity\Additive $additive) {
        $em= $this->_em;
        $additive->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($additive);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $additive;
    }

    public function updateAdditive(\OGIVE\AlertBundle\Entity\Additive $additive) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($additive);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $additive;
    }
    public function getAll($offset = null, $limit = null, $search_query = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', '?2'), $qb->expr()->like('lower(e.object)', '?2'), $qb->expr()->like('lower(e.owner)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getAllByString($search_query = null) {
        
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', '?2'), $qb->expr()->like('lower(e.object)', '?2'), $qb->expr()->like('lower(e.owner)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $search_query = strtolower($search_query);
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getAdditiveQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.reference', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
