<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * AlertProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertProcedureRepository extends \Doctrine\ORM\EntityRepository
{
}
