<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * ExpressionInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpressionInterestRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $expressionInterest->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $expressionInterest->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $expressionInterest;
    }

    public function updateExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $expressionInterest;
    }
    public function getAll($offset = null, $limit = null, $search_query = null, $start_date = null, $end_date = null, $owner = null, $domain = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', ':search_query'), $qb->expr()->like('lower(e.object)', ':search_query'), $qb->expr()->like('lower(e.owner)', ':search_query')
            ));
            $search_query = strtolower($search_query);
            $qb->setParameter('search_query', '%' . strtolower($search_query) . '%');
        }
        if ($start_date && $end_date) {
            $qb->andWhere(
                    $qb->expr()->between('e.publicationDate', ':start_date', ':end_date')
            );
            $start_date_DT = new \DateTime(date('Y-m-d H:i:s', strtotime(str_replace('/', '-', $start_date))));
            $end_date_DT = new \DateTime(date('Y-m-d H:i:s', strtotime(str_replace('/', '-', $end_date))));
            $qb->setParameter("start_date", $start_date_DT);
            $qb->setParameter("end_date", $end_date_DT);
        }
        if ($owner && $owner !="0") {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.owner)', ':owner'), $qb->expr()->like('e.owner', ':owner')
            ));
            $qb->setParameter('owner', '%' . $owner . '%');
        }
        if ($domain && $domain != "0") {
            $qb->join("e.domain", 'd');
            $qb->andWhere('d.id = :domain');
            $qb->setParameter("domain", intval($domain));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getAllByQueriedParameters($search_query = null, $start_date = null, $end_date = null, $owner = null, $domain = null) {
        
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', ':search_query'), $qb->expr()->like('lower(e.object)', ':search_query'), $qb->expr()->like('lower(e.owner)', ':search_query')
            ));
            $search_query = strtolower($search_query);
            $qb->setParameter('search_query', '%' . strtolower($search_query) . '%');
        }
        if ($start_date && $end_date) {
            $qb->andWhere(
                    $qb->expr()->between('e.publicationDate', ':start_date', ':end_date')
            );
            $start_date_DT = new \DateTime(date('Y-m-d H:i:s', strtotime(str_replace('/', '-', $start_date))));
            $end_date_DT = new \DateTime(date('Y-m-d H:i:s', strtotime(str_replace('/', '-', $end_date))));
            $qb->setParameter("start_date", $start_date_DT);
            $qb->setParameter("end_date", $end_date_DT);
        }
        if ($owner && $owner !="0") {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.owner)', ':owner'), $qb->expr()->like('e.owner', ':owner')
            ));
            $qb->setParameter('owner', '%' . $owner . '%');
        }
        if ($domain && $domain != "0") {
            $qb->join("e.domain", 'd');
            $qb->andWhere('d.id = :domain');
            $qb->setParameter("domain", intval($domain));
        }
        $qb->orderBy('e.createDate', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function getExpressionInterestQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.reference', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
