<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * ExpressionInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpressionInterestRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $expressionInterest->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $expressionInterest->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $expressionInterest;
    }

    public function updateExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($expressionInterest);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $expressionInterest;
    }
    public function getAll($offset=null, $limit=null) 
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = :status')
            ->orderBy('e.createDate', 'DESC')
            ->setParameter('status', 1);
        if($offset){
            $qb->setFirstResult($offset);
        }
        if($limit){
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getExpressionInterestQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.reference', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
