<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * HistoricalSubscriberSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalSubscriberSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteHistoricalSubscriberSubscription(\OGIVE\AlertBundle\Entity\HistoricalSubscriberSubscription $historicalSubscriberSubscription) {
        $em= $this->_em;
        $historicalSubscriberSubscription->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($historicalSubscriberSubscription);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveHistoricalSubscriberSubscription(\OGIVE\AlertBundle\Entity\HistoricalSubscriberSubscription $historicalSubscriberSubscription) {
        $em= $this->_em;
        $historicalSubscriberSubscription->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($historicalSubscriberSubscription);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $historicalSubscriberSubscription;
    }

    public function updateHistoricalSubscriberSubscription(\OGIVE\AlertBundle\Entity\HistoricalSubscriberSubscription $historicalSubscriberSubscription) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($historicalSubscriberSubscription);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $historicalSubscriberSubscription;
    }
    public function getAll($offset = null, $limit = null, $search_query = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.name)', '?2'), $qb->expr()->like('lower(e.phoneNumber)', '?2'), $qb->expr()->like('lower(e.email)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getAllByString($search_query = null) {
        
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.name)', '?2'), $qb->expr()->like('lower(e.phoneNumber)', '?2'), $qb->expr()->like('lower(e.email)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $search_query = strtolower($search_query);
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getHistoricalSubscriberSubscriptionQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
    
    public function getHistoricalSubscriberSubscriptionEnableOrDisableQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->setParameter('status', 1)
         ;
    }
}
