<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * ProcedureResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedureResultRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteProcedureResult(\OGIVE\AlertBundle\Entity\ProcedureResult $procedureResult) {
        $em= $this->_em;
        $procedureResult->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($procedureResult);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveProcedureResult(\OGIVE\AlertBundle\Entity\ProcedureResult $procedureResult) {
        $em= $this->_em;
        $procedureResult->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($procedureResult);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $procedureResult;
    }

    public function updateProcedureResult(\OGIVE\AlertBundle\Entity\ProcedureResult $procedureResult) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($procedureResult);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $procedureResult;
    }
    public function getAll($offset = null, $limit = null, $search_query = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', '?2'), $qb->expr()->like('lower(e.object)', '?2'), $qb->expr()->like('lower(e.owner)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getAllByString($search_query = null) {
        
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = ?1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.reference)', '?2'), $qb->expr()->like('lower(e.object)', '?2'), $qb->expr()->like('lower(e.owner)', '?2')
            ));
        }
        $qb->orderBy('e.createDate', 'DESC');
        if ($search_query) {
            $search_query = strtolower($search_query);
            $qb->setParameters(array(1 => 1, 2 => '%' . strtolower($search_query) . '%'));
        } else {
            $qb->setParameters(array(1 => 1));
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getProcedureResultQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.reference', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
