<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $subscriber->setStatus(0);
        $subscriber->setEntreprise(null);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $subscriber->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $subscriber;
    }

    public function updateSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $subscriber;
    }
    public function getAll() 
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = :status')
            ->orderBy('e.createDate', 'DESC')
            ->setParameter('status', 1);
        return $qb->getQuery()->getResult();
    }
    
    public function getSubscriberQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.name', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
