<?php

namespace OGIVE\AlertBundle\Repository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $subscriber->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $subscriber->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }

    public function updateSubscriber(\OGIVE\AlertBundle\Entity\Subscriber $subscriber) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($subscriber);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }
    public function getAll() 
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.status = :status')
           ->setParameter('status', 1);
        return $qb->getQuery()->getResult();
    }
    
    public function getSubscriberQueryBuilder() {
         return $this
          ->createQueryBuilder('s')
          ->where('s.status = :status')
          ->setParameter('status', 1);

    }
}
